version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.12.4.15
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      - CLICKHOUSE_DB=db
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=pass
    expose:
      - "8123"
      - "9000"
      - "9009"
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1' ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - clickhouse-utility

networks:
  clickhouse-utility: { }
